### ISSUE TITLE
Install script requires a way to specify python command

### ISSUE THREAD

**Issue by nogden** [cloxp/cloxp-install#1]
On Arch Linux the default Python version is Python 3. Since NPM requires version 2 I have to edit the install script and add `--python=python2` to the call to `npm install` in order to avoid installation errors. Either OS detection, or a way to specify the Python command for NPM would be useful.

**Comment by rksm** [comment]
Doesn't `PYTHON=python2.7 ./install.sh` work?

**Comment by nogden** [comment]
Yep. My bad. Perhaps just a note on the install instructions would be useful.
