### ISSUE TITLE
docker on mac : start.sh goes in infinite loop insatlling sqllite . 

### ISSUE THREAD

**Issue by pb-pravin** [cloxp/cloxp-install#7]
OS : mac osx

$ docker build --tag="cloxp" .
$ docker run -p 9001:9001 -t cloxp

Similar error when tried to install directly on Mac and Ubuntu without docker

///////
Problem installing npm package sqlite3:

> sqlite3@3.0.10 install /home/cloxp/LivelyKernel/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

make: Entering directory '/home/cloxp/LivelyKernel/node_modules/sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3081101/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3081101/sqlite3.o
  AR(target) Release/obj.target/deps/sqlite3.a
  COPY Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
node_sqlite3.target.mk:106: recipe for target 'Release/obj.target/node_sqlite3/src/database.o' failed
make: Leaving directory '/home/cloxp/LivelyKernel/node_modules/sqlite3/build'
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64' (1)

npm info it worked if it ends with ok
npm info using npm@2.14.2
npm info using node@v4.0.0
npm WARN package.json livelykernel@2.2.0 No license field.
npm info package.json babel-core@5.8.24 No README data
npm info package.json nrepl-client@0.2.3 No repository field.
npm info package.json optparse@1.0.5 No license field.
npm info package.json paredit.js@0.2.11 No repository field.
npm info package.json colorize@0.1.0 Invalid filename in 'files' list: 
npm info package.json colorize@0.1.0 No license field.
npm info package.json file-fuser@0.1.1 No repository field.
npm info package.json life_star@0.8.4 No license field.
npm info package.json lively-loader@0.2.5 No license field.
npm info package.json shelljs@0.2.6 No license field.
npm info package.json watch@0.8.0 No license field.
npm info package.json websocket@1.0.17 No license field.
npm info attempt registry request try #1 at 1:39:36 AM
npm http request GET https://registry.npmjs.org/sqlite3
npm http 304 https://registry.npmjs.org/sqlite3
npm info install sqlite3@3.0.10 into /home/cloxp/LivelyKernel
npm info installOne sqlite3@3.0.10
npm info preinstall sqlite3@3.0.10
npm info package.json node-pre-gyp@0.6.9 license should be a valid SPDX license expression
npm info attempt registry request try #1 at 1:39:37 AM
npm http request GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/nan
npm info install nan@1.8.4 into /home/cloxp/LivelyKernel/node_modules/sqlite3
npm info installOne nan@1.8.4
npm info preinstall nan@1.8.4
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/nan
npm info linkStuff nan@1.8.4
npm info install nan@1.8.4
npm info postinstall nan@1.8.4
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3
npm info linkStuff sqlite3@3.0.10
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp
npm info preinstall node-pre-gyp@0.6.9
npm info linkStuff node-pre-gyp@0.6.9
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/mkdirp
npm info preinstall mkdirp@0.5.1
npm info linkStuff mkdirp@0.5.1
npm info install mkdirp@0.5.1
npm info postinstall mkdirp@0.5.1
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/nopt
npm info preinstall nopt@3.0.3
npm info linkStuff nopt@3.0.3
npm info install nopt@3.0.3
npm info postinstall nopt@3.0.3
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/npmlog
npm info preinstall npmlog@1.2.1
npm info linkStuff npmlog@1.2.1
npm info install npmlog@1.2.1
npm info postinstall npmlog@1.2.1
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rc
npm info preinstall rc@1.1.0
npm info linkStuff rc@1.1.0
npm info install rc@1.1.0
npm info postinstall rc@1.1.0
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/request
npm info preinstall request@2.60.0
npm info linkStuff request@2.60.0
npm info install request@2.60.0
npm info postinstall request@2.60.0
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/rimraf
npm info preinstall rimraf@2.4.2
npm info linkStuff rimraf@2.4.2
npm info install rimraf@2.4.2
npm info postinstall rimraf@2.4.2
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/semver
npm info preinstall semver@5.0.1
npm info linkStuff semver@5.0.1
npm info install semver@5.0.1
npm info postinstall semver@5.0.1
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar
npm info preinstall tar@2.1.1
npm info linkStuff tar@2.1.1
npm info install tar@2.1.1
npm info postinstall tar@2.1.1
npm info build /home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/node_modules/tar-pack
npm info preinstall tar-pack@2.0.0
npm info linkStuff tar-pack@2.0.0
npm info install tar-pack@2.0.0
npm info postinstall tar-pack@2.0.0
npm info install node-pre-gyp@0.6.9
npm info postinstall node-pre-gyp@0.6.9
npm info install sqlite3@3.0.10
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.9
node-pre-gyp info using node@4.0.0 | linux | x64
node-pre-gyp info check checked for "/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" (not found)
node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v46-linux-x64.tar.gz
node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v46-linux-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.10/node-v46-linux-x64.tar.gz (falling back to source compile with node-gyp) 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.0.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.0.0 | linux | x64
gyp info spawn python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cloxp/LivelyKernel/node_modules/sqlite3/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/cloxp/.node-gyp/4.0.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/cloxp/.node-gyp/4.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/cloxp/LivelyKernel/node_modules/sqlite3',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.1
gyp info using node@4.0.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h:261:25: error: redefinition of 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)'
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: 'template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)' previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: 'node::smalloc' has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ',' or '...' before 'callback'
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(char_, size_t, int)':
../node_modules/nan/nan.h:665:50: error: 'callback' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: 'hint' was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(const char_, uint32_t)':
../node_modules/nan/nan.h:672:67: error: call of overloaded 'New(v8::Isolate_, const char_&, uint32_t&)' is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/database.h:11,
                 from ../src/database.cc:5:
/home/cloxp/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, v8::Localv8::String, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate_ isolate,
                                        ^
/home/cloxp/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from 'uint32_t {aka unsigned int}' to 'node::encoding'
/home/cloxp/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocalv8::Object node::Buffer::New(v8::Isolate_, char_, size_t) <near match>
 NODE_EXTERN v8::MaybeLocalv8::Object New(v8::Isolate\* isolate,
                                        ^
/home/cloxp/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from 'const char_' to 'char_'
In file included from ../src/database.h:11:0,
                 from ../src/database.cc:5:
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanNewBufferHandle(uint32_t)':
../node_modules/nan/nan.h:676:61: error: could not convert 'node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))' from 'v8::MaybeLocalv8::Object' to 'v8::Localv8::Object'
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function 'v8::Localv8::Object NanBufferUse(char_, uint32_t)':
../node_modules/nan/nan.h:683:12: error: 'Use' is not a member of 'node::Buffer'
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginOpen(node_sqlite3::Database::Baton_)':
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginClose(node_sqlite3::Database::Baton_)':
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginExec(node_sqlite3::Database::Baton_)':
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
../src/database.cc: In static member function 'static void node_sqlite3::Database::Work_BeginLoadExtension(node_sqlite3::Database::Baton_)':
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
     int status = uv_queue_work(uv_default_loop(),
         ^
make: *_\* [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.0.9-boot2docker
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64"
gyp ERR! cwd /home/cloxp/LivelyKernel/node_modules/sqlite3
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/cloxp/LivelyKernel/node_modules/sqlite3/lib/binding/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.0.9-boot2docker
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/cloxp/LivelyKernel/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/cloxp/LivelyKernel/node_modules/sqlite3
node-pre-gyp ERR! node -v v4.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
npm info sqlite3@3.0.10 Failed to exec install script
npm ERR! Linux 4.0.9-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "sqlite3"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.10 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.10 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.
npm info preuninstall sqlite3@3.0.10
npm info uninstall sqlite3@3.0.10
npm info postuninstall sqlite3@3.0.10

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cloxp/LivelyKernel/npm-debug.log

Finished installing lively server dependencies.
Checking if PartsBin exists...
...yes
module.js:338
    throw err;
    ^

Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/cloxp/LivelyKernel/node_modules/life_star/node_modules/lively-davfs/sqlite-storage.js:9:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
error: Forever detected script exited with code: 1
error: Script restart attempt #6
Not all required npm packages are installed! Installing packages sqlite3
Installing package sqlite3...

**Comment by rksm** [comment]
Thanks, I think there is currently a compat issue between sqlite and node v4.0.0.  It should work with an older version of node but I'll try to get this fixed next week with the new node.

**Comment by rksm** [comment]
should be fixed now
